<?php


/**
 * Skeleton subclass for performing query and update operations on the 'videos' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 05/10/13 19:13:15
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class VideosPeer extends BaseVideosPeer {

} // VideosPeer
