<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/05/10 19:12:34

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:host=localhost;dbname=sf_video',
  'username' => 'root',
  'password' => 'redalert',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
